In [62]:
import numpy as np

In [4]:
print(np.__version__)
np.show_config()

1.15.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [7]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
z = np.zeros(10)
print("%d bytes" % (z.size * z.itemsize))

80 bytes


In [11]:
np.info(np.add)
#np.add?  #此方法更为详细

In [12]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
t = z[::-1]
print(t)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
z = np.arange(0,9).reshape(3, 3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
z = np.nonzero([1,2,0,0,4,0]) #输出非0项的索引
print(z)

(array([0, 1, 4], dtype=int32),)


In [22]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
z = np.random.random((3,3,3))
print(z)

[[[0.7260796  0.94433141 0.74169035]
  [0.79273233 0.00102632 0.95909786]
  [0.62714641 0.26874091 0.67448462]]

 [[0.67981059 0.69140732 0.16410831]
  [0.55006398 0.99701529 0.97364168]
  [0.79374803 0.90119634 0.44902807]]

 [[0.76597853 0.59900173 0.10068678]
  [0.85454102 0.07512231 0.91865438]
  [0.74861578 0.01876505 0.89835817]]]


In [26]:
z = np.random.random((10, 10))
zMin = z.min()
zMax = z.max() #zMin, zMax = z.min(), z.max()
print(zMin, zMax)

0.0077065225626320455 0.976363958964547


In [29]:
z = np.random.random(30)
zMean = z.mean()
print(zMean)

0.5514639947795191


In [32]:
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
z = np.ones((5, 5))
z = np.pad(z, pad_width=1, mode="constant", constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [40]:
# np.nan是not a number ;np.inf是无穷大
print(0*np.nan) #nan
print(np.nan==np.nan) #False
print(np.inf>np.nan) #False 无穷大比任何数字都要大，但是无法和nan作比较
print(np.nan-np.nan) #nan
print(0.3==3*0.1) #False 3*0.1=0.30000...0004 

nan
False
False
nan
False


In [41]:
Z = np.diag(1+np.arange(4),k=-1) #返回对角线或者创建特殊对角线的数组
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [43]:
Z= np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
print(np.unravel_index(100,(6,7,8))) #numpy.unravel_index(indices, shape, order='C') 参数分别为索引值，形状，顺序

(1, 5, 4)


In [45]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) #np.tile对数组进行复制
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
z = np.random.random((5, 5))
z_max, z_min = z.max(), z.min()
z = (z-z_min)/(z_max-z_min)
print(z)

[[0.9067592  0.48413639 0.45243827 0.2191895  0.53932361]
 [0.42290844 0.6623156  0.08171434 0.69380829 0.45218787]
 [0.44949842 0.7656212  0.90277928 1.         0.43493289]
 [0.37720362 0.69132949 0.21994115 0.91446729 0.72249275]
 [0.46981986 0.         0.12788354 0.88945253 0.71813027]]


In [48]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [49]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))) #np.dot计算矩阵乘积
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [59]:
z = np.arange(10)
z[(z>3) &(z<=8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [63]:
print(sum(range(5),-1)) #python sum(iterabel [, start])
print(np.sum(range(5),-1)) #numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)

10
10


In [76]:
Z = np.arange(5)
#Z**Z  #[Z[0]**Z[0], Z[1]**Z[1], Z[2]**Z[2], Z[3]**Z[3], ...]
2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z #wrong

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [80]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [82]:
Z = np.random.uniform(-10,+10,10) #从均匀分布(概率分布为一条直线)中抽取样本，下限-10上限10
print (np.copysign(np.ceil(np.abs(Z)), Z)) #np.copysign改变符号值(把Z中符号值赋给前面的数组)np.ceil取上限np.abs绝对值

[ 3.47414426  9.71672037  9.9441949   2.27679301 -2.17053637  0.64719558
  0.60766217  4.12312464 -1.9372399  -2.20219694]
[ 4. 10. 10.  3. -3.  1.  1.  5. -2. -3.]


In [84]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2)
print(np.intersect1d(Z1,Z2)) #np.intersect1d找出两个数组的交集

[3 5 2 5 5 1 9 3 4 2] [4 8 4 7 1 5 5 8 0 4]
[1 4 5]


In [89]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# #An equivalent way, with a context manager:

with np.errstate(divide='ignore'):#忽略Numpy所有的警告
    Z = np.ones(1) / 0

In [91]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


In [92]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [93]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [95]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(np.add(A,B,out=B)) #out为结果的储存位置
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


In [96]:
Z = np.random.uniform(0,10,10)
#提取数组的整数部分
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[9. 3. 4. 5. 2. 4. 9. 9. 2. 5.]
[9. 3. 4. 5. 2. 4. 9. 9. 2. 5.]
[9. 3. 4. 5. 2. 4. 9. 9. 2. 5.]
[9 3 4 5 2 4 9 9 2 5]
[9. 3. 4. 5. 2. 4. 9. 9. 2. 5.]


In [97]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [98]:
def generate():
    for x in range(10):
        yield x #一个函数包含 yield 表达式，那么它是一个生成器函数；调用它会返回一个特殊的迭代器，称为生成器
Z = np.fromiter(generate(),dtype=float,count=-1) #从可迭代对象中创建新的一维数组
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [101]:
Z = np.linspace(0,1,11,endpoint=False)[1:] #从左端点开始，在指定区间内返回均匀间隔的数字，可以排除又端点
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [102]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.38155231 0.40420585 0.41075454 0.46628593 0.51340006 0.55063056
 0.57778423 0.58651851 0.60615486 0.8147026 ]


In [103]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [104]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B) #如果两个数组在容差范围内在元素方面相等，则返回True。
print(equal)
#方法2
equal = np.array_equal(A,B)
print(equal)

False


In [105]:
Z = np.zeros(10)
Z.flags.writeable = False #数组只读，对其进行修改则报错
Z[0] = 1

ValueError: assignment destination is read-only

In [106]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.11488395 0.24290407 1.26612227 0.71332222 0.66296704 0.70605411
 1.03718499 0.7283857  0.90939409 1.13743945]
[0.66238528 0.24224852 0.69531002 0.85492302 0.82803417 1.36761208
 1.05359528 1.49215609 1.56798982 0.76390275]


In [107]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 #z.argmax()返回最大值的标签
print (Z)

[0.         0.89916431 0.64467422 0.38275061 0.95556888 0.59153834
 0.32987769 0.84918069 0.74245209 0.30910533]


In [108]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5)) #从坐标向量返回坐标矩阵
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [109]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [110]:
 for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

 for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [111]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [112]:
 Z = np.arange(100)
 v = np.random.uniform(0,100)
 index = (np.abs(Z-v)).argmin()
 print (Z[index])

21


In [113]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [115]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)
# 方法2
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.57274444 0.56200107 0.50564165 0.53927845 0.71488354
  0.34645571 0.15471101 0.16857963 0.70380877]
 [0.57274444 0.         0.26807011 0.51232696 0.07098502 0.57108989
  0.75271943 0.63556366 0.72449903 0.60689645]
 [0.56200107 0.26807011 0.         0.71302794 0.32056396 0.81671634
  0.84244499 0.67923756 0.66979023 0.84499648]
 [0.50564165 0.51232696 0.71302794 0.         0.44149392 0.2159763
  0.39432966 0.42495706 0.66025482 0.19829369]
 [0.53927845 0.07098502 0.32056396 0.44149392 0.         0.50435292
  0.69399737 0.58773999 0.69773527 0.53846647]
 [0.71488354 0.57108989 0.81671634 0.2159763  0.50435292 0.
  0.5960257  0.64092126 0.87352733 0.05582733]
 [0.34645571 0.75271943 0.84244499 0.39432966 0.69399737 0.5960257
  0.         0.19174916 0.41537338 0.55981459]
 [0.15471101 0.63556366 0.67923756 0.42495706 0.58773999 0.64092126
  0.19174916 0.         0.25178856 0.61924661]
 [0.16857963 0.72449903 0.66979023 0.66025482 0.69773527 0.87352733
  0.41537338 0.2517885

In [116]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [118]:
#Z = np.genfromtxt()#从文本文件加载数据，并按指定处理缺失值。
np.genfromtxt?

In [119]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z): #np.ndenumerate() 返回一个迭代器，产生一对数组坐标和值。
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [120]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [121]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1) #在数组内随机放p个元素
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [123]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.25975529  0.23601487 -0.27163836 -0.13867382 -0.11919199 -0.18365993
  -0.30919501 -0.16541174  0.08188461  0.61011608]
 [ 0.27467242 -0.49833345  0.10343242 -0.17751452  0.45182795  0.11135463
  -0.46443048  0.10703252  0.17298132 -0.08102281]
 [-0.17396005 -0.44941165  0.11853608 -0.24127509  0.23986035  0.42555739
  -0.03771728 -0.30772417  0.22141028  0.20472415]
 [ 0.37005306 -0.24695445  0.455298   -0.30436386  0.25751657 -0.27976932
   0.22915093 -0.10337179 -0.06537949 -0.31217964]
 [ 0.06399363 -0.36492151  0.2672365   0.26494206  0.15719819 -0.5127974
  -0.48811931  0.08601811  0.30632382  0.22012591]]


In [124]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[7 9 2]
 [9 1 9]
 [9 5 8]]
[[9 1 9]
 [9 5 8]
 [7 9 2]]


In [128]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [129]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.4916747927651327


In [130]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [132]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [134]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 1. 4. 4. 3. 2. 3. 4. 2.]


In [135]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [136]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [137]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[64 64 49 56]
 [42 45 52 42]
 [57 43 55 66]]


In [138]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.62503689 0.52894561 0.62493558 0.52723399 0.48886306 0.60360608
 0.48064164 0.42754699 0.63446743 0.52557213]


In [139]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([2.07368325, 2.41040574, 1.86028773, 0.92769221, 1.50946973])

In [140]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [141]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [142]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [143]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 6, 26) ( 6, 64) ( 7, 41) ( 7, 70) (10, 29) (10, 85) (16, 24) (16, 55)
 (17, 32) (17, 41) (24, 55) (26, 64) (27, 69) (27, 71) (28, 55) (28, 75)
 (29, 85) (30, 96) (30, 97) (32, 41) (41, 70) (50, 51) (50, 53) (50, 77)
 (50, 96) (51, 77) (53, 96) (55, 75) (69, 71) (96, 97)]


In [144]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [145]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [146]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [147]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1])

In [148]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 3.37612917  2.17387472  6.51935656 12.65842547 13.3152266  10.32699641
  8.64069701  4.60274719  6.45776221  3.71668953]


In [150]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.58036791  1.38373573 13.03974364  9.56788444 12.0678983   2.20474623
   2.9113483  12.69760948  2.89092688  3.89191662]
 [ 5.13606776  5.73494926  6.37810628  1.45905444  8.52719223  5.3287064
   7.55466262  4.38442601  8.28436789  5.85163542]
 [ 4.37564499  4.41913199  8.38762959  1.85478013  9.59954058  3.05757853
   4.41088725  6.88942412  4.9234965   2.91800877]
 [ 4.6647437  14.93672026  1.6264533   0.59631367  0.95556637 12.68760913
   3.7829257   2.27142008  9.20240517 10.73796356]
 [ 3.46871653  6.07397985  9.3812019  12.37359648  7.09620839  0.95222511
   6.62864289 10.06195056  3.99678812  2.49037748]
 [ 4.02122484  0.50016532 13.60841653  8.53652369 13.04402067  2.62960394
   1.69775441 12.97765427  2.23249423  3.84446948]
 [ 5.08966044  3.95202878  8.7073439   1.3891473  10.10931342  2.80608368
   4.97119535  7.07174124  5.20032269  2.8937816 ]
 [ 5.98541948 11.41020717  3.47227821  8.28063405  2.01254331  7.00518886
   3.42061042  3.92683734  1.26655035  3.61712035]
 

In [151]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[4 3 7 2 7 6 5 1 7 9]
 [8 8 3 8 1 5 3 6 6 2]
 [7 2 0 8 1 9 9 1 3 8]
 [2 7 8 1 8 4 4 3 9 8]
 [6 4 0 7 4 3 1 3 3 2]
 [2 9 8 9 4 6 8 3 7 7]
 [5 4 2 5 1 1 2 5 1 6]
 [4 9 4 8 0 4 1 6 0 7]
 [9 8 3 9 0 4 4 8 3 5]
 [2 5 8 5 3 1 6 0 3 4]]
[[0 0 0 0 0]
 [0 4 3 7 2]
 [0 8 8 3 8]
 [0 7 2 0 8]
 [0 2 7 8 1]]


c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [152]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [153]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [154]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

0


In [156]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[3 4 0]
   [0 3 3]
   [3 2 2]]

  [[4 0 2]
   [3 3 4]
   [2 2 2]]

  [[0 2 2]
   [3 4 0]
   [2 2 4]]

  [[2 2 0]
   [4 0 2]
   [2 4 0]]

  [[2 0 0]
   [0 2 1]
   [4 0 0]]

  [[0 0 0]
   [2 1 1]
   [0 0 2]]

  [[0 0 1]
   [1 1 3]
   [0 2 3]]

  [[0 1 1]
   [1 3 2]
   [2 3 2]]]


 [[[0 3 3]
   [3 2 2]
   [3 1 3]]

  [[3 3 4]
   [2 2 2]
   [1 3 1]]

  [[3 4 0]
   [2 2 4]
   [3 1 1]]

  [[4 0 2]
   [2 4 0]
   [1 1 1]]

  [[0 2 1]
   [4 0 0]
   [1 1 0]]

  [[2 1 1]
   [0 0 2]
   [1 0 1]]

  [[1 1 3]
   [0 2 3]
   [0 1 4]]

  [[1 3 2]
   [2 3 2]
   [1 4 2]]]


 [[[3 2 2]
   [3 1 3]
   [3 1 2]]

  [[2 2 2]
   [1 3 1]
   [1 2 2]]

  [[2 2 4]
   [3 1 1]
   [2 2 2]]

  [[2 4 0]
   [1 1 1]
   [2 2 0]]

  [[4 0 0]
   [1 1 0]
   [2 0 4]]

  [[0 0 2]
   [1 0 1]
   [0 4 3]]

  [[0 2 3]
   [0 1 4]
   [4 3 2]]

  [[2 3 2]
   [1 4 2]
   [3 2 1]]]


 [[[3 1 3]
   [3 1 2]
   [1 2 0]]

  [[1 3 1]
   [1 2 2]
   [2 0 0]]

  [[3 1 1]
   [2 2 2]
   [0 0 2]]

  [[1 1 1]
   [2 2 0]
   [0 2 1]]

  [[1 1 0]
   

In [157]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 1 18 14  4 13]
 [18  9  7 10  8]
 [14  7  7 42 13]
 [ 4 10 42  2 15]
 [13  8 13 15  0]]


In [159]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [160]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [161]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0

In [162]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [163]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [164]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [165]:
x = np.random.rand()
np.power(x,3) # x*x*x或者np.einsum('i,i,i->i',x,x,x)

0.06387981739791769

In [167]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[2 3 4]


In [168]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[4 1 2]
 [3 0 4]
 [2 3 2]
 [2 1 0]
 [1 1 4]
 [2 2 4]
 [2 3 4]
 [2 2 3]
 [3 4 3]
 [0 4 2]]
[[4 1 2]
 [3 0 4]
 [2 3 2]
 [2 1 0]
 [1 1 4]
 [2 2 4]
 [2 3 4]
 [2 2 3]
 [3 4 3]
 [0 4 2]]


In [169]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [170]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


In [172]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
6.464554746363302
A * B
[0.19479486 0.59617006 0.36006827 0.13211277 0.02074233 0.32588713
 0.05692577 0.01738207 0.53204297 0.75083931]
inner
2.9869655425147372
outer
[[1.94794862e-01 2.44292211e-01 2.41007548e-01 6.79656643e-02
  1.85102947e-01 1.35815547e-01 7.21569103e-02 7.08800810e-03
  2.08041115e-01 3.31795102e-01]
 [4.75376856e-01 5.96170056e-01 5.88154171e-01 1.65863224e-01
  4.51724733e-01 3.31443896e-01 1.76091530e-01 1.72975559e-02
  5.07702977e-01 8.09711873e-01]
 [2.91025942e-01 3.64975598e-01 3.60068269e-01 1.01541547e-01
  2.76546101e-01 2.02910114e-01 1.07803320e-01 1.05895721e-02
  3.10816009e-01 4.95706002e-01]
 [3.78645435e-01 4.74859193e-01 4.68474409e-01 1.32112769e-01
  3.59806133e-01 2.64000480e-01 1.40259781e-01 1.37777860e-02
  4.04393718e-01 6.44948740e-01]
 [2.18283945e-02 2.73749869e-02 2.70069128e-02 7.61612152e-03
  2.07423344e-02 1.52192688e-02 8.08578571e-03 7.94270630e-04
  2.33127481e-02 3.71804180e-02]
 [4.67407000e-01 5.86175061e-01 5.78293565e

In [173]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [174]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [175]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.15872642  0.21993239]
